document.write('<style type="text/css">.z0{color: #5B5B5B; font-size: 9pt; font-weight: 700}.t0{width: 10%; text-align: center}</style>');
document.write('<div style="width: 100%; background-color: #FFFFFF">');
document.write('<table style="width: 80%; height: 64px; margin: 0px auto" cellspacing="0" cellpadding="0">');
document.write('<tr><td style="height: 5px" colspan="10">　</td></tr>');
document.write('<tr>');
document.write('<td class="t0"><a title="古典小说·古典散文·古典戏曲·古典诗词" href="/gdwx/index.htm"><span class="z0">古典文学</span></a></td>');
document.write('<td class="t0"><a title="现代文学名著" href="/xdwx/index.htm"><span class="z0">现代文学</span></a></td>');
document.write('<td class="t0"><a title="历代名家作品集" href="/mj/index.htm"><span class="z0">名家文集</span></a></td>');
document.write('<td class="t0"><a title="历史·二十四史" href="/ls/index.htm"><span class="z0">史籍历史</span></a></td>');
document.write('<td class="t0"><a href="/"><span class="z0">虚阁首页</span></a></td>');
document.write('<td class="t0"><a title="言情小说" href="/yq/index.htm"><span class="z0">言情小说</span></a></td>');
document.write('<td class="t0"><a title="侦探小说名家作品集·侦探名著·悬疑小说" href="/zt/index.htm"><span class="z0">侦探推理</span></a></td>');
document.write('<td class="t0"><a href="/js/index.htm"><span class="z0">军事军旅</span></a></td>');
document.write('<td class="t0"><a href="/kh/index.htm"><span class="z0">科幻小说</span></a></td>');
document.write('<td class="t0"><a title="时尚阅读·流行前沿" href="/cx/index.htm"><span class="z0">时尚阅读</span></a></td></tr>');
document.write('<tr><td  class="t0"><a title="国外名著·外国名家作品集" href="/wgwx/index.htm"><span class="z0">外国名著</span></a></td>');
document.write('<td class="t0"><a title="人物传记·纪实文学·历史小说" href="/zj/index.htm"><span class="z0">传记纪实</span></a></td>');
document.write('<td  class="t0"><a title="香港、台湾、海外作家作品" href="/gt/index.htm"><span class="z0">港台文学</span></a></td>');
document.write('<td  class="t0"><a title="诗歌·古代词·民歌·国外诗歌" href="/sc/index.htm"><span class="z0">诗词歌赋</span></a></td>');
document.write('<td  class="t0"><span class="z0"><a title="古典小说·古典散文·古典戏曲·古典诗词" href="/gdwx/xs/index.htm"><span style="color: #5B5B5B">古典小说</span></a></span></td>');
document.write('<td  class="t0"><a title="武侠名家作品集、武侠名著" href="/wuxia/index.htm"><span class="z0">武侠小说</span></a></td><td class="t0"><a href="/xh/index.htm"><span class="z0">玄幻奇侠</span></a></td>');
document.write('<td  class="t0"><a title="影视原著·影视小说" href="/ysyz/index.htm"><span class="z0">影视小说</span></a></td>');
document.write('<td class="t0"><a title="时空穿越·宫闱情仇·女生小说" href="/cy/index.htm"><span class="z0">穿越宫闱</span></a></td>');
document.write('<td  class="t0"><a title="青春·校园小说" href="/xy/index.htm"><span class="z0">青春校园</span></a></td>');
document.write('</tr></table></div>');
document.writeln("<div style=\'height: 6px; background-color: #FFFFFF\'></div>");